#!/usr/bin/env bash
# Configure nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/WairimuMaringa permanent;/" /etc/nginx/sites-available/default
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/error_simple.html;/1" /etc/nginx/sites-available/default
sudo sed -i "s/^server\s{/server {\n\tadd_header X-Served-By $HOSTNAME;/1" /etc/nginx/sites-available/default
sudo service nginx start
