#!/usr/bin/env bash
# install nginx web server and configure HA proxy
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy
sudo chown -R ubuntu /etc/haproxy/
echo -e "\n# Configure frontend (http) listen all *:80 and solve with backend (my-servers)\\nfrontend http\\n\tbind *:80\\n\tmode http\
\n\tdefault_backend my-servers\\n\\n# Configure all server availables for frontend (http)\\nbackend my-servers\\n\tbalance roundrobin\
\n\tserver 63775-web-01 54.160.102.228 check\
\n\tserver 63775-web-02 52.91.121.211 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
