#!/usr/bin/env bash
# Script tht generates mysql dump
db_user='root'
db_password=$1
db_script='backup.sql'
db_name_backup=$(date +%d-%m-%Y).tar.gz
mysqldump --all-databases -u "$db_user" -p"$db_password" > "$db_script"
tar -czvf "$db_name_backup" "$db_script"
