#!/usr/bin/env bash
# Sharpening debugging skills
sudo sed -i "s/listen 8080 /listen 80 /" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 /listen \[::\]:80 /" /etc/nginx/sites-enabled/default
sudo service nginx restart
