#!/usr/bin/env bash
# Script displaying 1 to 100 with given conditions
for (( x = 1; x<=100; x++))
do
	if [ $((x % 5)) -eq 0 ] && [ $((x % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x%3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((x%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $x
	fi
done
